### ISSUE TITLE
使用STM32F103ZET6写入有问题

### ISSUE THREAD

**Issue by zeroL-C** [zifengchenll/circular_buffer#1]
我用keil搭建工程，使用你的例程打印输出没问题，但是我设置环形缓冲大小为512时，数据数量设置大于15时，写入便无反应，程序变会进入到HardFault_Handler(void)函数中（STM32HAL库函数），此实验我在windos c平台验证能正常使用，但是在keil STM32上不能如愿运行。

**Comment by zifengchenll** [comment]
有检测一些平台配置的宏定义吗？使用FreeRTOS还是裸机，另一个配置看是否使用了锁，port.c文件是否已经适配了锁相关函数

**Comment by zeroL-C** [comment]
[STM32F103ZET6.zip](https://github.com/user-attachments/files/16404195/STM32F103ZET6.zip)
我使用的是裸机，cubemx生成的工程，当缓冲大小配置为512时，就有问题，麻烦你能看看吗？

**Comment by zifengchenll** [comment]
可以的，我周末看一下

**Comment by zeroL-C** [comment]
> 可以的，我周末看一下
已经解决了，忘记设置堆栈大小了不好意思
